### ISSUE TITLE
Error E04269

### ISSUE THREAD

**Issue by mariaritamelillo** [kwart/ldap-server#4]
Hi,
thanks for your work. I've installed this project as jar on Win7 and run (with JDK 1.7 64 bit) as 
**java -jar ldap-server.jar -b 0.0.0.0 -p 389 conf.ldif** 
and It works perfectly: the Ldap server start in a few second

I've installed same jar on Centos 6.5 64 bit and run it with JDK 1.7 using the same command, but Ldap Server not start and the output is:

```
[main] WARN org.apache.directory.api.ldap.model.entry.DefaultEntry - The attribute 'samaaccountname' cannot be stored
Exception in thread "main" org.apache.directory.api.ldap.model.exception.LdapNoSuchAttributeException: ERR_04269 ATTRIBUTE_TYPE for OID samaaccountname does not exist!
        at org.apache.directory.api.ldap.model.schema.registries.DefaultAttributeTypeRegistry.lookup(DefaultAttributeTypeRegistry.java:293)
        at org.apache.directory.api.ldap.model.schema.registries.DefaultAttributeTypeRegistry.lookup(DefaultAttributeTypeRegistry.java:47)
        at org.apache.directory.api.ldap.schema.manager.impl.DefaultSchemaManager.lookupAttributeTypeRegistry(DefaultSchemaManager.java:1604)
        at org.apache.directory.api.ldap.model.entry.DefaultEntry.<init>(DefaultEntry.java:311)
        at org.jboss.test.ldap.LdapServer.importLdif(LdapServer.java:142)
        at org.jboss.test.ldap.LdapServer.importLdif(LdapServer.java:132)
        at org.jboss.test.ldap.LdapServer.<init>(LdapServer.java:88)
        at org.jboss.test.ldap.LdapServer.main(LdapServer.java:69)
Caused by: org.apache.directory.api.ldap.model.exception.LdapException: ERR_04269 ATTRIBUTE_TYPE for OID samaaccountname does not exist!
        at org.apache.directory.api.ldap.model.schema.registries.DefaultSchemaObjectRegistry.lookup(DefaultSchemaObjectRegistry.java:176)
        at org.apache.directory.api.ldap.model.schema.registries.DefaultAttributeTypeRegistry.lookup(DefaultAttributeTypeRegistry.java:289)
        ... 7 more
```

The jar and conf.ldif are the same on Win7 and Centos 6.5, so I don't know why the jar do not work on Linux.
I don't know if I've forgotten some configuration/requirements needed for installation on Linux.

Thanks in advance for help.

**Comment by kwart** [comment]
Could you share a sample ldif which causes the problem?

**Comment by kwart** [comment]
Closing. The `samaaccountname` is an Active Directory attribute. It's not included in the Apache DS.
You could probably hack it somehow by importing the schema, but it's not intention of this project.
See this SO answer if you look for more details: https://serverfault.com/a/915747/174150
